BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL,
	"Sex"	INTEGER,
	"Weight"	INTEGER,
	"Height"	INTEGER,
	"Age"	INTEGER,
	"Activity"	REAL,
	"DietID"	INTEGER,
	FOREIGN KEY("DietID") REFERENCES "Diet"("ID")
);
CREATE TABLE IF NOT EXISTS "Ingredient" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Proteins"	REAL NOT NULL,
	"Fats"	REAL NOT NULL,
	"Carbohydrates"	REAL NOT NULL,
	"Calories"	REAL NOT NULL,
	"Cost"	REAL NOT NULL,
	"Image"	BLOB
);
CREATE TABLE IF NOT EXISTS "Dish" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"AuthorID"	TEXT,
	"Recipe"	TEXT,
	"Image"	REAL,
	FOREIGN KEY("AuthorID") REFERENCES "User"("ID")
);
CREATE TABLE IF NOT EXISTS "Qualities" (
	"PropertyID"	INTEGER NOT NULL,
	"DishID"	INTEGER NOT NULL,
	FOREIGN KEY("PropertyID") REFERENCES "Property"("ID"),
	FOREIGN KEY("DishID") REFERENCES "Dish"("ID")
);
CREATE TABLE IF NOT EXISTS "Limitations" (
	"DietID"	INTEGER NOT NULL,
	"PropertyID"	INTEGER NOT NULL,
	FOREIGN KEY("DietID") REFERENCES "Diet"("ID"),
	FOREIGN KEY("PropertyID") REFERENCES "Property"("ID")
);
CREATE TABLE IF NOT EXISTS "Compositions" (
	"IngredientID"	INTEGER NOT NULL,
	"DishID"	INTEGER NOT NULL,
	"Quantity"	REAL NOT NULL,
	FOREIGN KEY("IngredientID") REFERENCES "Ingredient"("ID"),
	FOREIGN KEY("DishID") REFERENCES "Dish"("ID")
);
CREATE TABLE IF NOT EXISTS "Menu" (
	"UserID"	INTEGER NOT NULL,
	"DishID"	INTEGER NOT NULL,
	"day"	INTEGER NOT NULL,
	"Quantity"	REAL NOT NULL,
	FOREIGN KEY("UserID") REFERENCES "User"("ID"),
	FOREIGN KEY("DishID") REFERENCES "Dish"("ID")
);
CREATE TABLE IF NOT EXISTS "Diet" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL,
	"Description"	TEXT
);
CREATE TABLE IF NOT EXISTS "Property" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Description"	TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "QualitiesIndex" ON "Qualities" (
	"PropertyID",
	"DishID"
);
CREATE UNIQUE INDEX IF NOT EXISTS "LimitationsIndex" ON "Limitations" (
	"DietID",
	"PropertyID"
);
CREATE UNIQUE INDEX IF NOT EXISTS "CompositionsIndex" ON "Compositions" (
	"DishID",
	"IngredientID"
);
CREATE INDEX IF NOT EXISTS "MenuIndex" ON "Menu" (
	"UserID",
	"DishID"
);
COMMIT;
